# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Feedback.me' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Feedback.me
  pod 'ScrollableGraphView'

  target 'Feedback.meTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Feedback.meUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
